default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USER'] || ''  %>
  password: <%= ENV['DB_PASSWORD'] || '' %>
  host: <%= (ENV['DB_HOST'] || 'localhost').to_json %>

development:
  <<: *default
  database: planner_development
  pool: 5

test:
  <<: *default
  database: planner_test
  pool: 5

production:
  <<: *default
  database: planner
  pool: 5
